import type { Locale } from "@/lib/i18n";

type Localized = readonly [string, string, string, string, string];

const names: Record<string, Localized> = {
    "Respiración 4-7-8": ["Respiración 4-7-8", "Respiration 4-7-8", "Respiração 4-7-8", "4-7-8 breathing", "Respirazione 4-7-8"],
    "Respiración lateral": ["Respiración lateral", "Respiration latérale", "Respiração lateral", "Side breathing", "Respirazione laterale"],
    "Estiramiento de cuello": ["Estiramiento de cuello", "Étirement du cou", "Alongamento do pescoço", "Neck stretch", "Allungamento del collo"],
    "Relajación de hombros": ["Relajación de hombros", "Détente des épaules", "Relaxamento dos ombros", "Shoulder release", "Rilassamento delle spalle"],
    "Círculos de hombros": ["Círculos de hombros", "Cercles d’épaules", "Círculos com os ombros", "Shoulder circles", "Circonduzioni delle spalle"],
    "Torsión suave de espalda": ["Torsión suave de espalda", "Torsion douce du dos", "Torção suave das costas", "Gentle back twist", "Torsione dolce della schiena"],
    "Gato-vaca": ["Gato-vaca", "Chat-vache", "Gato-vaca", "Cat-cow", "Gatto-mucca"],
    "Estiramiento de pecho": ["Estiramiento de pecho", "Étirement de la poitrine", "Alongamento do peito", "Chest stretch", "Allungamento del petto"],
    "Inclinaciones laterales": ["Inclinaciones laterales", "Flexions latérales", "Inclinações laterais", "Side bends", "Piegamenti laterali"],
    "Círculos de cadera": ["Círculos de cadera", "Cercles de hanches", "Círculos com o quadril", "Hip circles", "Circonduzioni delle anche"],
    "Estiramiento de isquiotibiales sentado": ["Estiramiento de isquiotibiales sentado", "Étirement des ischio-jambiers assis", "Alongamento sentado dos posteriores da coxa", "Seated hamstring stretch", "Allungamento dei posteriori della coscia da seduti"],
    "Mariposa sentado": ["Mariposa sentado", "Papillon assis", "Borboleta sentada", "Seated butterfly", "Farfalla da seduti"],
    "Rodillas al pecho": ["Rodillas al pecho", "Genoux vers la poitrine", "Joelhos ao peito", "Knees to chest", "Ginocchia al petto"],
    "Relajación facial": ["Relajación facial", "Détente du visage", "Relaxamento facial", "Face release", "Rilassamento del viso"],
    "Abrazo con respiración": ["Abrazo con respiración", "Étreinte respirée", "Abraço com respiração", "Breathing hug", "Abbraccio con il respiro"],
    "Bostezo con estiramiento": ["Bostezo con estiramiento", "Bâillement et étirement", "Bocejo com alongamento", "Yawn and stretch", "Sbadiglio e allungamento"],
    "Postura de la montaña": ["Postura de la montaña", "Posture de la montagne", "Postura da montanha", "Mountain pose", "Posizione della montagna"],
    "Respiración profunda": ["Respiración profunda", "Respiration profonde", "Respiração profunda", "Deep breathing", "Respirazione profonda"],
    "Marcha en el sitio": ["Marcha en el sitio", "Marche sur place", "Marcha no lugar", "March in place", "Marcia sul posto"],
    "Rotación de brazos": ["Rotación de brazos", "Rotation des bras", "Rotação dos braços", "Arm rotations", "Rotazioni delle braccia"],
    "Jumping jack suave": ["Jumping jack suave", "Jumping jack doux", "Polichinelo leve", "Low-impact jumping jacks", "Jumping jack leggero"],
    "Sentadillas suaves": ["Sentadillas suaves", "Squats doux", "Agachamentos leves", "Gentle squats", "Squat leggeri"],
    "Zancadas alternas": ["Zancadas alternas", "Fentes alternées", "Avanços alternados", "Alternating lunges", "Affondi alternati"],
    "Puente de glúteos": ["Puente de glúteos", "Pont fessier", "Elevação de quadril", "Glute bridge", "Ponte per i glutei"],
    "Escaladores lentos": ["Escaladores lentos", "Mountain climbers lents", "Escaladores lentos", "Slow mountain climbers", "Mountain climber lenti"],
    "Flexiones en pared": ["Flexiones en pared", "Pompes au mur", "Flexões na parede", "Wall push-ups", "Piegamenti al muro"],
    "Supermán": ["Supermán", "Superman", "Super-homem", "Superman", "Superman"],
    "Rebotes ligeros": ["Rebotes ligeros", "Petits rebonds", "Pequenos saltitos", "Gentle bounces", "Rimbalzi leggeri"],
    "Caminata lenta en el sitio": ["Caminata lenta en el sitio", "Marche lente sur place", "Caminhada lenta no lugar", "Slow walk in place", "Camminata lenta sul posto"],
    "Estiramiento al despertar": ["Estiramiento al despertar", "Étirement au réveil", "Alongamento ao acordar", "Wake-up stretch", "Allungamento al risveglio"],
    "Respiración en caja": ["Respiración en caja", "Respiration carrée", "Respiração quadrada", "Box breathing", "Respirazione quadrata"],
};

const instructions: Record<string, Localized> = {
    "Respiración 4-7-8": ["Siéntate cómodo. Inhala 4, sostén 7 y exhala 8. Repite suavemente.", "Asseyez-vous confortablement. Inspirez 4 secondes, retenez 7, expirez 8. Répétez doucement.", "Sente-se confortavelmente. Inspire por 4, segure por 7 e expire por 8. Repita suavemente.", "Sit comfortably. Inhale for 4, hold for 7, and exhale for 8. Repeat gently.", "Siediti comodamente. Inspira per 4, trattieni per 7 ed espira per 8. Ripeti con calma."],
    "Respiración lateral": ["Siéntate erguido. Inhala despacio y exhala contando hasta 6; lleva el aire a un lado del pecho y cambia.", "Asseyez-vous droit. Inspirez lentement, expirez en comptant jusqu’à 6 vers un côté de la poitrine, puis changez.", "Sente-se ereto. Inspire devagar e expire contando até 6, levando o ar a um lado do peito; depois troque.", "Sit tall. Inhale slowly, then exhale for 6 toward one side of your chest. Switch sides gently.", "Siediti dritto. Inspira lentamente ed espira contando fino a 6 verso un lato del petto, poi cambia."],
    "Estiramiento de cuello": ["Inclina la oreja hacia el hombro durante 15 segundos. Cambia de lado sin forzar.", "Inclinez l’oreille vers l’épaule pendant 15 secondes. Changez de côté sans forcer.", "Incline a orelha em direção ao ombro por 15 segundos. Troque de lado sem forçar.", "Tilt your ear toward your shoulder for 15 seconds. Switch sides without forcing it.", "Inclina l’orecchio verso la spalla per 15 secondi. Cambia lato senza forzare."],
    "Relajación de hombros": ["Eleva los hombros hacia las orejas, sostén 3 segundos y suéltalos. Repite 5 veces respirando despacio.", "Haussez les épaules vers les oreilles, maintenez 3 secondes puis relâchez. Répétez 5 fois en respirant lentement.", "Eleve os ombros em direção às orelhas, segure por 3 segundos e solte. Repita 5 vezes respirando devagar.", "Lift your shoulders toward your ears, hold for 3 seconds, then release. Repeat 5 times with slow breaths.", "Solleva le spalle verso le orecchie, mantieni per 3 secondi e rilascia. Ripeti 5 volte respirando lentamente."],
    "Círculos de hombros": ["Eleva los hombros y haz círculos amplios hacia delante y hacia atrás, sin tensar el cuello.", "Haussez les épaules et faites de grands cercles vers l’avant puis l’arrière, sans tendre le cou.", "Eleve os ombros e faça círculos amplos para frente e para trás, sem tensionar o pescoço.", "Raise your shoulders and make wide circles forward and backward without tensing your neck.", "Solleva le spalle e fai ampi cerchi in avanti e indietro, senza tendere il collo."],
    "Torsión suave de espalda": ["Sentado, gira el torso hacia un lado con una mano apoyada. Mantén 10 segundos y cambia.", "Assis, tournez le buste d’un côté en prenant appui avec une main. Maintenez 10 secondes, puis changez.", "Sentado, gire o tronco para um lado apoiando uma mão. Mantenha por 10 segundos e troque.", "While seated, gently turn your torso to one side with one hand supported. Hold for 10 seconds, then switch.", "Da seduto, ruota il busto da un lato appoggiando una mano. Mantieni per 10 secondi, poi cambia."],
    "Gato-vaca": ["A cuatro apoyos, redondea la espalda al inhalar y arquea suavemente al exhalar. Muévete despacio.", "À quatre pattes, arrondissez le dos à l’inspiration et creusez-le doucement à l’expiration. Bougez lentement.", "Em quatro apoios, arredonde as costas ao inspirar e arqueie suavemente ao expirar. Mova-se devagar.", "On hands and knees, round your back as you inhale and gently arch as you exhale. Move slowly.", "A quattro zampe, incurva la schiena inspirando e inarcala dolcemente espirando. Muoviti lentamente."],
    "Estiramiento de pecho": ["Entrelaza las manos detrás de la espalda y abre el pecho. Mantén 20 segundos respirando hondo.", "Entrelacez les mains derrière le dos et ouvrez la poitrine. Maintenez 20 secondes en respirant profondément.", "Entrelace as mãos atrás das costas e abra o peito. Mantenha por 20 segundos respirando fundo.", "Clasp your hands behind your back and open your chest. Hold for 20 seconds with deep breaths.", "Intreccia le mani dietro la schiena e apri il petto. Mantieni per 20 secondi respirando profondamente."],
    "Inclinaciones laterales": ["Eleva un brazo e inclínate suavemente hacia el lado contrario. Vuelve al centro y cambia.", "Levez un bras et penchez-vous doucement du côté opposé. Revenez au centre et changez de côté.", "Eleve um braço e incline-se suavemente para o lado oposto. Volte ao centro e troque.", "Raise one arm and gently lean to the opposite side. Return to center and switch sides.", "Solleva un braccio e inclinati dolcemente dal lato opposto. Torna al centro e cambia lato."],
    "Círculos de cadera": ["De pie, con las manos en la cintura, dibuja círculos amplios con la cadera en ambos sentidos.", "Debout, les mains sur les hanches, dessinez de grands cercles avec le bassin dans les deux sens.", "Em pé, com as mãos na cintura, faça círculos amplos com o quadril nos dois sentidos.", "Stand with your hands on your hips and make wide circles in both directions.", "In piedi, con le mani sui fianchi, disegna ampi cerchi in entrambe le direzioni."],
    "Estiramiento de isquiotibiales sentado": ["Siéntate con las piernas extendidas e inclina el pecho hacia las rodillas sin forzar. Mantén 20 segundos.", "Assis, jambes tendues, penchez le torse vers les genoux sans forcer. Maintenez 20 secondes.", "Sente-se com as pernas estendidas e aproxime o peito dos joelhos sem forçar. Mantenha por 20 segundos.", "Sit with your legs extended and lean your chest toward your knees without forcing it. Hold for 20 seconds.", "Siediti con le gambe distese e avvicina il petto alle ginocchia senza forzare. Mantieni per 20 secondi."],
    "Mariposa sentado": ["Junta las plantas de los pies y deja caer las rodillas. Sujeta los pies y respira con suavidad.", "Joignez les plantes des pieds et laissez tomber les genoux. Tenez vos pieds et respirez doucement.", "Una as plantas dos pés e deixe os joelhos caírem. Segure os pés e respire suavemente.", "Bring the soles of your feet together and let your knees relax outward. Hold your feet and breathe gently.", "Unisci le piante dei piedi e lascia rilassare le ginocchia verso l’esterno. Tieni i piedi e respira dolcemente."],
    "Rodillas al pecho": ["Tumbado, abraza una rodilla contra el pecho durante 15 segundos. Cambia de pierna sin levantar la cabeza.", "Allongé, ramenez un genou contre la poitrine pendant 15 secondes. Changez de jambe sans lever la tête.", "Deitado, abrace um joelho contra o peito por 15 segundos. Troque de perna sem levantar a cabeça.", "Lying down, hug one knee to your chest for 15 seconds. Switch legs without lifting your head.", "Sdraiato, abbraccia un ginocchio al petto per 15 secondi. Cambia gamba senza sollevare la testa."],
    "Relajación facial": ["Aprieta suavemente ojos, mandíbula y hombros durante 3 segundos; suelta. Repite 6 veces.", "Contractez doucement les yeux, la mâchoire et les épaules pendant 3 secondes, puis relâchez. Répétez 6 fois.", "Contraia suavemente os olhos, a mandíbula e os ombros por 3 segundos; solte. Repita 6 vezes.", "Gently tighten your eyes, jaw, and shoulders for 3 seconds, then release. Repeat 6 times.", "Contrai delicatamente occhi, mandibola e spalle per 3 secondi, poi rilassa. Ripeti 6 volte."],
    "Abrazo con respiración": ["Cruza los brazos sobre el pecho y aprieta suavemente. Inhala 4 y exhala 6 con los ojos cerrados.", "Croisez les bras sur la poitrine et serrez doucement. Inspirez 4 secondes et expirez 6, les yeux fermés.", "Cruze os braços sobre o peito e abrace-se suavemente. Inspire por 4 e expire por 6 de olhos fechados.", "Cross your arms over your chest and give yourself a gentle squeeze. Inhale for 4, exhale for 6 with eyes closed.", "Incrocia le braccia sul petto e stringiti dolcemente. Inspira per 4 ed espira per 6 a occhi chiusi."],
    "Bostezo con estiramiento": ["Bosteza mientras estiras los brazos hacia arriba. Alarga la exhalación para soltar tensión.", "Bâillez en étirant les bras vers le haut. Prolongez l’expiration pour relâcher les tensions.", "Boceje enquanto estica os braços para cima. Alongue a expiração para aliviar a tensão.", "Yawn as you stretch your arms overhead. Lengthen your exhale to release tension.", "Sbadiglia mentre allunghi le braccia verso l’alto. Prolunga l’espirazione per sciogliere la tensione."],
    "Postura de la montaña": ["Separa los pies al ancho de los hombros, brazos a los lados y mirada al frente. Respira con calma.", "Écartez les pieds à la largeur des épaules, bras le long du corps, regard devant. Respirez calmement.", "Afaste os pés na largura dos ombros, braços ao lado do corpo e olhar à frente. Respire com calma.", "Stand with feet shoulder-width apart, arms by your sides, and gaze forward. Breathe calmly.", "Tieni i piedi alla larghezza delle spalle, le braccia lungo i fianchi e lo sguardo avanti. Respira con calma."],
    "Respiración profunda": ["Inhala contando 4, haz una pausa de 2 y exhala contando 6. Sigue el ritmo del círculo.", "Inspirez en comptant jusqu’à 4, faites une pause de 2, puis expirez jusqu’à 6. Suivez le cercle.", "Inspire contando até 4, pause por 2 e expire contando até 6. Acompanhe o ritmo do círculo.", "Inhale for 4, pause for 2, then exhale for 6. Follow the circle’s rhythm.", "Inspira contando fino a 4, fai una pausa di 2 ed espira fino a 6. Segui il ritmo del cerchio."],
    "Marcha en el sitio": ["Marcha elevando las rodillas a la altura de la cadera. Mueve los brazos al ritmo de la respiración.", "Marchez sur place en levant les genoux à hauteur des hanches. Balancez les bras au rythme du souffle.", "Marche no lugar elevando os joelhos até a altura do quadril. Mova os braços no ritmo da respiração.", "March in place, lifting your knees to hip height. Move your arms with your breathing.", "Marcia sul posto sollevando le ginocchia all’altezza dei fianchi. Muovi le braccia seguendo il respiro."],
    "Rotación de brazos": ["Extiende los brazos a los lados y haz círculos suaves hacia delante y luego hacia atrás.", "Tendez les bras sur les côtés et faites de petits cercles, d’abord vers l’avant puis vers l’arrière.", "Estenda os braços para os lados e faça círculos suaves, primeiro para frente e depois para trás.", "Extend your arms out to the sides and make gentle circles forward, then backward.", "Allunga le braccia lateralmente e fai piccoli cerchi, prima in avanti e poi indietro."],
    "Jumping jack suave": ["Abre y cierra brazos y piernas dando pasos laterales en lugar de saltar. Mantén un ritmo estable.", "Ouvrez et refermez bras et jambes avec des pas latéraux plutôt que des sauts. Gardez un rythme régulier.", "Abra e feche braços e pernas dando passos laterais em vez de saltar. Mantenha um ritmo constante.", "Open and close your arms and legs with side steps instead of jumps. Keep a steady pace.", "Apri e chiudi braccia e gambe con passi laterali invece di saltare. Mantieni un ritmo regolare."],
    "Sentadillas suaves": ["Baja como si fueras a sentarte, con las rodillas alineadas sobre los pies. Sube sin bloquearlas.", "Descendez comme pour vous asseoir, genoux alignés avec les pieds. Remontez sans verrouiller les genoux.", "Desça como se fosse sentar, com os joelhos alinhados aos pés. Suba sem travá-los.", "Lower as if sitting in a chair, keeping your knees aligned over your feet. Rise without locking them.", "Scendi come per sederti, mantenendo le ginocchia allineate ai piedi. Risali senza bloccarle."],
    "Zancadas alternas": ["Da un paso adelante y baja con ambas rodillas flexionadas. Regresa y alterna las piernas con control.", "Faites un pas en avant et fléchissez les deux genoux. Revenez et alternez les jambes avec contrôle.", "Dê um passo à frente e flexione os dois joelhos. Volte e alterne as pernas com controle.", "Step forward and bend both knees. Return and alternate legs with control.", "Fai un passo avanti e piega entrambe le ginocchia. Torna indietro e alterna le gambe con controllo."],
    "Puente de glúteos": ["Tumbado con las rodillas flexionadas, eleva la cadera activando los glúteos. Baja despacio y repite.", "Allongé, genoux pliés, soulevez les hanches en contractant les fessiers. Redescendez lentement et répétez.", "Deitado com os joelhos flexionados, eleve o quadril contraindo os glúteos. Desça devagar e repita.", "Lie with knees bent, lift your hips by squeezing your glutes, then lower slowly and repeat.", "Sdraiato con le ginocchia piegate, solleva il bacino contraendo i glutei. Abbassa lentamente e ripeti."],
    "Escaladores lentos": ["En posición de plancha, lleva una rodilla al pecho lentamente y alterna. Mantén el abdomen firme.", "En planche, ramenez lentement un genou vers la poitrine, puis alternez. Gardez le ventre engagé.", "Na posição de prancha, leve um joelho ao peito devagar e alterne. Mantenha o abdômen firme.", "From a plank, slowly bring one knee toward your chest and alternate. Keep your core steady.", "In plank, porta lentamente un ginocchio al petto e alterna. Mantieni attivi gli addominali."],
    "Flexiones en pared": ["Apoya las manos en la pared a la altura de los hombros. Acerca el pecho y mantén la espalda recta.", "Placez les mains au mur à hauteur des épaules. Approchez la poitrine du mur en gardant le dos droit.", "Apoie as mãos na parede na altura dos ombros. Aproxime o peito mantendo as costas retas.", "Place your hands on the wall at shoulder height. Bring your chest closer while keeping your back straight.", "Appoggia le mani al muro all’altezza delle spalle. Avvicina il petto mantenendo la schiena dritta."],
    "Supermán": ["Tumbado boca abajo, eleva brazos y piernas durante 3 segundos y baja. Mantén el cuello relajado.", "Allongé sur le ventre, levez bras et jambes pendant 3 secondes puis relâchez. Gardez le cou détendu.", "Deitado de barriga para baixo, eleve braços e pernas por 3 segundos e desça. Relaxe o pescoço.", "Lie face down, lift your arms and legs for 3 seconds, then lower. Keep your neck relaxed.", "Sdraiato a pancia in giù, solleva braccia e gambe per 3 secondi, poi abbassa. Rilassa il collo."],
    "Rebotes ligeros": ["Haz rebotes muy suaves sobre las puntas de los pies. Mantén las rodillas flexibles y respira con calma.", "Faites de petits rebonds sur la pointe des pieds. Gardez les genoux souples et respirez calmement.", "Faça pequenos saltitos na ponta dos pés. Mantenha os joelhos flexíveis e respire com calma.", "Make very gentle bounces on the balls of your feet. Keep your knees soft and breathe steadily.", "Fai piccoli rimbalzi sulle punte dei piedi. Mantieni le ginocchia morbide e respira con calma."],
    "Caminata lenta en el sitio": ["Camina muy despacio en el sitio y nota cómo cada pie toca el suelo. Mantén el movimiento.", "Marchez très lentement sur place et sentez chaque pied toucher le sol. Continuez jusqu’à la fin.", "Caminhe bem devagar no lugar, percebendo cada pé tocar o chão. Continue durante o exercício.", "Walk very slowly in place and notice each foot meeting the floor. Keep going for the exercise.", "Cammina lentamente sul posto e nota ogni piede appoggiarsi a terra. Continua per tutta la durata."],
    "Estiramiento al despertar": ["Estira los brazos hacia arriba y alarga el cuerpo sobre las puntas de los pies. Suelta con un bostezo.", "Étirez les bras vers le haut et allongez le corps sur la pointe des pieds. Relâchez avec un bâillement.", "Estique os braços para cima e alongue o corpo na ponta dos pés. Relaxe com um bocejo.", "Reach your arms overhead and lengthen your body onto your toes. Release with a yawn.", "Allunga le braccia verso l’alto e il corpo sulla punta dei piedi. Rilassa con uno sbadiglio."],
    "Respiración en caja": ["Inhala contando 4, sostén 4, exhala 4 y espera 4. Repite hasta terminar.", "Inspirez 4 secondes, retenez 4, expirez 4 et attendez 4. Répétez jusqu’à la fin.", "Inspire por 4, segure por 4, expire por 4 e aguarde por 4. Repita até terminar.", "Inhale for 4, hold for 4, exhale for 4, and wait for 4. Repeat until the exercise ends.", "Inspira per 4, trattieni per 4, espira per 4 e attendi per 4. Ripeti fino alla fine."],
};

const localeIndex: Record<Locale, number> = { es: 0, fr: 1, pt: 2, en: 3, it: 4 };

export function localizeExercise(name: string, instruction: string | null | undefined, locale: Locale) {
    const index = localeIndex[locale];
    return {
        name: names[name]?.[index] ?? name,
        instruction: !instruction || locale === "es" ? instruction : instructions[name]?.[index] ?? instruction,
    };
}
