import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import HomeScreen from "./HomeScreen";

const { push, signOutMock, isWeekendDayMock } = vi.hoisted(() => ({ push: vi.fn(), signOutMock: vi.fn(), isWeekendDayMock: vi.fn(() => false) }));
vi.mock("next/navigation", () => ({ useRouter: () => ({ push }) }));
vi.mock("next-auth/react", () => ({ signOut: signOutMock }));
vi.mock("@/lib/utils", async (importOriginal) => { const actual = await importOriginal<typeof import("@/lib/utils")>(); return { ...actual, isWeekendDay: isWeekendDayMock }; });
vi.mock("@/lib/i18n", () => ({ useI18n: () => ({ locale: "es", t: (key: string, values: Record<string, string | number> = {}) => { const map: Record<string, string> = { homeGreeting: "Un momento para ti", homeSubline: "Bloom adapta tu día", yourBloom: "Tu Bloom", checkins: "registros", todayRecommendation: "Bloom para hoy", whyToday: "Por qué hoy", startSession: "Comenzar", checkinLabel: "Check-in", checkinQuestion: "¿Cómo llegas hoy?", journalPrompt: "¿Quieres guardar algo de hoy?", energy: "Energía", stress: "Estrés", journal: "Nota", notePlaceholder: "Añade", focus_balance: "Encontrar equilibrio", focus_balance_detail: "Un poco", moodStressed: "Estresada", moodStressedHint: "Soltar tensión", moodAnxious: "Ansiosa", moodAnxiousHint: "Bajar", moodEnergetic: "Energética", moodEnergeticHint: "Usar", moodUnmotivated: "Sin motivación", moodUnmotivatedHint: "Empezar", moodAria: "Registro de ánimo", plantAlt: "Planta de Bloom — etapa {stage} de {max}", todayIsLogged: "Hoy ya está registrado", readyForMovement: "Tu sesión te espera", readyForMovementDetail: "Retomar", viewEvolution: "Ver evolución", recentCare: "Tus últimos días", signOut: "Salir", urgentHelp: "Ayuda urgente (SOS)", weekend: "Fin de semana", weekendAria: "Fin de semana", weekendIntro: "Paseo", shortWalk: "Paseo corto", freshAir: "10–15 min", easyBike: "Bici suave", steadyMovement: "Movimiento", activeRest: "Descanso activo", unhurriedWalk: "Caminar", recordRide: "Registrar paseo del fin de semana", rideThanks: "Paseo registrado", weekendGentleDetail: "Cuenta", calmMode: "Modo calma", close: "Cerrar", calmIntro: "Pausa", talkSomeone: "Hablar", breatheWithMe: "Respirar", externalSupport: "Apoyo", breathingGuide: "Respira", calmTip: "Consejo", noRecord: "Sin registro", noData: "Sin datos", streakDays: "Racha {count} días", days: "días", achievementsTitle: "Logros", achievementsEmpty: "Sigue", gardenBeginning: "Aquí empieza", gardenSprouting: "Brota", gardenGrowing: "Crece", gardenBlooming: "Florece" }; const template = map[key] ?? key; return Object.entries(values).reduce((text, [name, value]) => text.replaceAll(`{${name}}`, String(value)), template); }, automatic: true, setLanguage: vi.fn() }) }));

const fetchMock = vi.fn();
let weekendRide = false;
let checkedIn = false;

beforeEach(() => {
  push.mockReset(); signOutMock.mockReset(); isWeekendDayMock.mockReturnValue(false); weekendRide = false; checkedIn = false; fetchMock.mockReset();
  fetchMock.mockImplementation((input: string) => { const url = String(input); if (url.startsWith("/api/log")) return Promise.resolve({ ok: true, json: async () => ({ checkedIn, weekendRide, workoutDone: false, energy: 3, stress: 3, note: "" }) }); if (url.startsWith("/api/plant")) return Promise.resolve({ ok: true, json: async () => ({ stage: 2, careDays: 2, minutes: 0, completedSessions: 0, growthPercent: 17, achievements: [] }) }); if (url.startsWith("/api/history")) return Promise.resolve({ ok: true, json: async () => ({ history: [] }) }); if (url.startsWith("/api/profile")) return Promise.resolve({ ok: true, json: async () => ({ profile: { onboardingCompleted: true, preferredDuration: 15 } }) }); if (url.startsWith("/api/checkin")) return Promise.resolve({ ok: true, json: async () => ({ ok: true, stage: 3 }) }); if (url.startsWith("/api/ride")) return Promise.resolve({ ok: true, json: async () => ({ ok: true, stage: 3 }) }); if (url.startsWith("/api/sos")) return Promise.resolve({ ok: true, json: async () => ({ ok: true }) }); return Promise.resolve({ ok: true, json: async () => ({}) }); });
  vi.stubGlobal("fetch", fetchMock);
});
afterEach(() => vi.unstubAllGlobals());

describe("HomeScreen premium", () => {
  it("carga el nuevo home y los cuatro ánimos", async () => { render(<HomeScreen />); expect(await screen.findByText("Bloom para hoy")).toBeInTheDocument(); expect(screen.getAllByRole("button", { name: /ansiosa/i })).toHaveLength(1); });
  it("registra el check-in y navega con contexto de sesión", async () => { render(<HomeScreen />); fireEvent.click(await screen.findByRole("button", { name: /ansiosa/i })); await waitFor(() => expect(push).toHaveBeenCalledWith("/move?mood=Ansiosa&energy=3&stress=3&duration=15")); expect(fetchMock).toHaveBeenCalledWith("/api/checkin", expect.objectContaining({ method: "POST" })); });
  it("con doble toque solo envía un check-in", async () => { render(<HomeScreen />); const button = await screen.findByRole("button", { name: /ansiosa/i }); fireEvent.click(button); fireEvent.click(button); await waitFor(() => expect(fetchMock.mock.calls.filter(([url]) => url === "/api/checkin")).toHaveLength(1)); });
  it("preserva el flujo de paseo de fin de semana", async () => { isWeekendDayMock.mockReturnValue(true); render(<HomeScreen />); fireEvent.click(await screen.findByRole("button", { name: /registrar paseo/i })); expect(await screen.findByText("Paseo registrado")).toBeInTheDocument(); expect(fetchMock.mock.calls.some(([url]) => url === "/api/ride")).toBe(true); weekendRide = true; });
  it("abre SOS", async () => { render(<HomeScreen />); fireEvent.click(await screen.findByRole("button", { name: /ayuda urgente/i })); expect(await screen.findByRole("dialog")).toBeInTheDocument(); });
});
